### ISSUE TITLE
Is it still relevant for current versions of EET?

### ISSUE THREAD

**Issue by abalabokhin** [EE-Mod-Setup/EET_Fixpack#2]
Hi, do you know the fixes from this mod already in EET (version from github) or not? I am trying to figure out shall I recomment installing this mod with any EET assembly or not.

**Comment by RoxanneSHS** [comment]
I am using https://github.com/Gibberlings3/EET/archive/refs/heads/master.zip for my installations together with the fixpack and I observe no problems. I am no longer monitoring EET progress (if there is any...) but there is nothing done by the fixes that may cause issues - at worst things may be redundant.
You have to decided yourself since I am no longer active other than to fix obvious bugs in my own mods.
